#KubeJS Dev Properties
#Mon Jun 29 14:56:17 EDT 2026
logSkippedTags=false
logSkippedRecipes=false
logSkippedPlugins=true
debugInfo=true
strictTags=false
logAddedRecipes=false
logRemovedRecipes=false
logModifiedRecipes=false
logInvalidRecipeHandlers=true
dataPackOutput=false
logGeneratedData=false
logErroringRecipes=true
alwaysCaptureErrors=false
